s_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
#s_arm/gazebo_ros_control/pid_gains:
#  joint_1: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}



